### ISSUE TITLE
token

### ISSUE THREAD

**Issue by SoonyangZhang** [sumory/gru#5]
你好，请问，你的业务token是怎么获取的？好疑惑。

**Comment by sumory** [comment]
业务系统更要先到`ticket`申请访问`spear`的token，请求`ticket`的示例如下：

```
http://192.168.1.100:30000/ticket?userId=1&userName=sumory&appType=9&token1=f9f05cad90a584ad6df98f4b64be98f3

参数说明：
userId 整型，用户uid
userName 字符串，用户名称
appType 字符串，约定的用于某个业务的标识
token1 字符串，按照与ticket模块约定的算法生成的token, 生成策略为md5(${userId}_${userName}_${appType}_${salt})，${salt}值为业务模块与`ticket`模块约定的一个盐
```

`ticket`中验证以上逻辑的代码如下：
[https://github.com/sumory/gru/blob/master/ticket/src/main/java/com/sumory/gru/ticket/server/HttpHandler.java#L100](https://github.com/sumory/gru/blob/master/ticket/src/main/java/com/sumory/gru/ticket/server/HttpHandler.java#L100)

**Comment by SoonyangZhang** [comment]
谢谢您的回答。在聊天系统中，假设A在spear1，B注册到spear2，A向B发消息，spear1怎么讲消息路由到B呢？靠数据库吗？也很疑惑。

**Comment by sumory** [comment]
spear节点之间通过消息中间件交互消息，你可以选择redis、rocketmq的方式来通信，也可以自行扩展接口，详细请看spear模块配置和介绍
